version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
    # Eliminamos la sección 'volumes' para evitar sobrescribir los datos de MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: > 
      sh -c "php project/laravel/artisan serve --host 0.0.0.0 --port 8000" 
    volumes:
      - ./laravel:/var/www/html/project
    depends_on:
      - db
    links:
      - db:mysql

volumes:
  db_data:
